import { Product, ProductTypes } from "../models/product.model";
export class ProductService {
    private products : Product[] = [
      {  id: '1',
        name: 'golden',
        description: 'smth',
        price: 120,
        quantity: 20,
        rating: 4,
        image: '/cauldrons/golden_cauldron.jpeg',
        type: ProductTypes.Cauldron,
        deliveryTime: 0,
        reviews: [
          {authorId: 0, authorName: 'jo', rating: 3, reviewText: 'nice but i blew it up', date: new Date(), orderId: 12345},
          {authorId: 2, authorName: 'jojo', rating: 5, reviewText: 'amazing', date: new Date(), orderId:1111111111}
        ],
      },
        {id: '2',
          name: 'silver',
          description: 'smth',
          price: 120,
          quantity: 12,
          rating: 0,
          image: '/cauldrons/silver_cauldron.jpeg',
          type: ProductTypes.Cauldron,
          deliveryTime: 0,
          reviews: [],
         },
          {id: '3',
            name: 'iron',
            description: 'smth',
            price: 300,
            quantity: 4,
            rating: 4.8,
            image: '/cauldrons/iron_cauldron.avif',
            type: ProductTypes.Cauldron,
            deliveryTime: 22,
            reviews: [],
          },
            {id: '4',
              name: 'wow',
              description: 'smth',
              price: 10,
              quantity: 5,
              rating: 2.5,
              image: '/cauldrons/iron_cauldron.avif',
              type: ProductTypes.Cauldron,
              deliveryTime: 10,
              reviews: [],
          },
          {  id: '5',
            name: 'vetiver',
            description: 'smth',
            price: 120,
            quantity: 20,
            rating: 4,
            image: '/herbs/herbs_thick_bundle.jpg',
            type: ProductTypes.Herb,
            deliveryTime: 0,
            reviews: [
              {authorId: 0, authorName: 'jo', rating: 3, reviewText: 'nice but i blew it up', date: new Date(), orderId: 12345},
              {authorId: 2, authorName: 'jojo', rating: 5, reviewText: 'amazing', date: new Date(), orderId:1111111111}
            ],
          },
            {id: '6',
              name: 'grass',
              description: 'smth',
              price: 120,
              quantity: 12,
              rating: 0,
              image: '/herbs/thin_bundle.jpg',
              type: ProductTypes.Herb,
              deliveryTime: 0,
              reviews: [],
             },
              {id: '7',
                name: 'mint',
                description: 'smth',
                price: 300,
                quantity: 4,
                rating: 4.8,
                image: '/herbs/thin_bundle.jpg',
                type: ProductTypes.Herb,
                deliveryTime: 22,
                reviews: [],
              },
                {id: '8',
                  name: 'powerful dimond',
                  description: 'smth',
                  price: 10,
                  quantity: 5,
                  rating: 2.5,
                  image: '/cauldrons/iron_cauldron.avif',
                  type: ProductTypes.Cauldron,
                  deliveryTime: 10,
                  reviews: [],
              },
              {  id: '9',
                name: 'fireFlower',
                description: 'smth',
                price: 120,
                quantity: 20,
                rating: 4,
                image: '/herbs/herbs_thick_bundle.jpg',
                type: ProductTypes.Herb,
                deliveryTime: 0,
                reviews: [
                  {authorId: 0, authorName: 'jo', rating: 3, reviewText: 'nice but i blew it up', date: new Date(), orderId: 12345},
                  {authorId: 2, authorName: 'jojo', rating: 5, reviewText: 'amazing', date: new Date(), orderId:1111111111}
                ],
              },
                {id: '10',
                  name: 'Cursed dandelion',
                  description: 'smth',
                  price: 120000,
                  quantity: 12,
                  rating: 0,
                  image: '/herbs/herbs_thick_bundle.jpg',
                  type: ProductTypes.Herb,
                  deliveryTime: 0,
                  reviews: [],
                 },
                  {id: '11',
                    name: 'Bloody',
                    description: 'smth',
                    price: 300,
                    quantity: 4,
                    rating: 4.8,
                    image: '/cauldrons/iron_cauldron.avif',
                    type: ProductTypes.Cauldron,
                    deliveryTime: 22,
                    reviews: [],
                  },
                    {id: '12',
                      name: 'Mountain vine',
                      description: 'smth',
                      price: 10,
                      quantity: 5,
                      rating: 2.5,
                      image: '/herbs/herbs_thick_bundle.jpg',
                      type: ProductTypes.Herb,
                      deliveryTime: 10,
                      reviews: [],
                  },
                  {  id: '13',
                    name: 'Encrusted',
                    description: 'smth',
                    price: 120,
                    quantity: 20,
                    rating: 4,
                    image: '/cauldrons/golden_cauldron.jpeg',
                    type: ProductTypes.Cauldron,
                    deliveryTime: 0,
                    reviews: [
                      {authorId: 0, authorName: 'jo', rating: 3, reviewText: 'nice but i blew it up', date: new Date(), orderId: 12345},
                      {authorId: 2, authorName: 'jojo', rating: 5, reviewText: 'amazing', date: new Date(), orderId:1111111111}
                    ],
                  },
                    {id: '14',
                      name: 'silver weed',
                      description: 'smth',
                      price: 120,
                      quantity: 12,
                      rating: 0,
                      image: '/cauldrons/silver_cauldron.jpeg',
                      type: ProductTypes.Herb,
                      deliveryTime: 0,
                      reviews: [],
                     },
                      {id: '15',
                        name: 'all-seeing sunflower',
                        description: 'smth',
                        price: 300,
                        quantity: 4,
                        rating: 4.8,
                        image: '/herbs/herbs_thick_bundle.jpg',
                        type: ProductTypes.Herb,
                        deliveryTime: 22,
                        reviews: [],
                      },
                        {id: '16',
                          name: 'pitless pot',
                          description: 'smth',
                          price: 10,
                          quantity: 5,
                          rating: 2.5,
                          image: '/cauldrons/iron_cauldron.avif',
                          type: ProductTypes.Cauldron,
                          deliveryTime: 10,
                          reviews: [],
                      },
      ];

    errorText:string ='';

    getProducts() : Product[] { return this.products;};
    getProductById(id:string):Product { return  this.products.find((product)=> product.id==id)!;};

    getMaxPrice() : number { return Math.max(...this.products.map(product => product.price))}
    getMinPrice() : number { return Math.min(...this.products.map(product => product.price))}
    getMinDeliveryTime() : number { return Math.min(...this.products.map(product => product.deliveryTime))}

    calculateRating(product : Product) {
      const nOfReviews = product.reviews.length
      product.rating = Math.round(product.reviews.reduce((sum, rev) => sum + rev.rating, 0) * 10 / nOfReviews) / 10
    }
}